apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mandelbrot-coordinator
  template:
    metadata:
      labels:
        app: mandelbrot-coordinator
    spec:
      containers:
        - name: mandelbrot-coordinator
          image: quantum-core:latest
          imagePullPolicy: Never
          env:
            - name: ROLE
              value: "coordinator"
            - name: REGISTRATION_ADDR
              value: "0.0.0.0:9000"
