apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mandelbrot-coordinator
  template:
    metadata:
      labels:
        app: mandelbrot-coordinator
    spec:
      containers:
        - name: mandelbrot-coordinator
          image: quantum-core:latest
          imagePullPolicy: Never
          env:
            - name: ROLE
              value: "coordinator"
            - name: WORKERS
              value: >-
                worker-0.worker-headless.default.svc.cluster.local:8080,
                worker-1.worker-headless.default.svc.cluster.local:8080,
                worker-2.worker-headless.default.svc.cluster.local:8080,
                worker-3.worker-headless.default.svc.cluster.local:8080,
                worker-4.worker-headless.default.svc.cluster.local:8080,
                worker-5.worker-headless.default.svc.cluster.local:8080,
                worker-6.worker-headless.default.svc.cluster.local:8080,
                worker-7.worker-headless.default.svc.cluster.local:8080,
                worker-8.worker-headless.default.svc.cluster.local:8080,
                worker-9.worker-headless.default.svc.cluster.local:8080,
                worker-10.worker-headless.default.svc.cluster.local:8080,
                worker-11.worker-headless.default.svc.cluster.local:8080,
                worker-12.worker-headless.default.svc.cluster.local:8080,
                worker-13.worker-headless.default.svc.cluster.local:8080,
                worker-14.worker-headless.default.svc.cluster.local:8080,
                worker-15.worker-headless.default.svc.cluster.local:8080,
                worker-16.worker-headless.default.svc.cluster.local:8080,
                worker-17.worker-headless.default.svc.cluster.local:8080,
                worker-18.worker-headless.default.svc.cluster.local:8080,
                worker-19.worker-headless.default.svc.cluster.local:8080
