apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker
spec:
  serviceName: worker-headless # must match the headless service name above
  replicas: 20
  selector:
    matchLabels:
      app: mandelbrot-worker
  template:
    metadata:
      labels:
        app: mandelbrot-worker
    spec:
      containers:
        - name: mandelbrot-worker
          image: quantum-core:latest
          imagePullPolicy: Never
          env:
            - name: ROLE
              value: "worker"
            - name: LISTEN_ADDR
              value: "0.0.0.0:8080"
